#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by convert.sh from run_rec.txt
# Run one aggregated boss job for all filtered raw files.

echo "[run] /afs/ihep.ac.cn/users/y/yanjiazhen/besfs5/geant4/tutorial/BESIII_PhoenixCheck/data/convert_work/batch_run_rec/rec/batch.txt"
cd "/afs/ihep.ac.cn/users/y/yanjiazhen/besfs5/geant4/tutorial/BESIII_PhoenixCheck/data/convert_work/batch_run_rec/rec" && boss.exe "batch.txt"

